### ISSUE TITLE
Fails to parse peer IPv6 address from UAPI

### ISSUE THREAD

**Issue by endreszabo** [cmusatyalab/wireguard-tools#13]
I just briefly tested the lib to see if it would fit my use-cases.

I have a `wireguard-go` (=UAPI interface) running an interface, with an IPv6 peer. Upon getting the config, the parse is getting back a bracketed IPv6 address that it fails to parse.

```python
>>> import wireguard_tools
>>> a=list(wireguard_tools.WireguardDevice.list())
>>> a[0].get_config()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    a[0].get_config()
  File ".../wireguard_tools/wireguard_uapi.py", line 70, in get_config
    peer.endpoint_host = ip_address(addr)
                         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: '[fd4d:4045:e5e8:100:25f7:1436:6d38:9315]' does not appear to be an IPv4 or IPv6 address
```

The raw UAPI config the lib is getting from the socket is like:

```sh
$ socat unix-connect:/var/run/wireguard/test.sock  -
get=1

private_key=388450801deb7070e7fc60f8410c0a7040fb4e0a798e8791da9ee2222430734f
listen_port=4444
public_key=abe5f674fb1007fb392b3f82a8a80e009bae0f7e29f0b107ebad2a0b3e58fa5a
preshared_key=0000000000000000000000000000000000000000000000000000000000000000
protocol_version=1
endpoint=[fd4d:4045:e5e8:100:25f7:1436:6d38:9315]:46929
last_handshake_time_sec=1723565511
last_handshake_time_nsec=668395459
tx_bytes=65352
rx_bytes=808504
persistent_keepalive_interval=0
errno=0
```

(I also have a feeling that the library would have issues with empty (nonexistent) AllowedIPs.)

**Comment by gaby** [comment]
I had the same issue recently, had to manually change my .conf

**Comment by jaharkes** [comment]
About to commit a fix for this, I believe an empty AllowedIPs should be fine as the WireguardPeer instance is instantiated with an empty list that is simply never appended to in that case.
